# This is a sample workflow to test or replace with your source code.
#
# This workflow returns a list of Wikipedia articles related to a search term.
# The search term is retrieved from a Cloud Function that returns the current day of the week
# (in GMT), unless a search term is given as input (e.g. {"searchTerm": "Monday"}).
main:
    params: [input]
    steps:
        - fetchTweets:
            call: http.get
            args:
                url: https://api.twitter.com/1.1/search/tweets.json?q=filter%3Alinks%20-filter%3Areplies%20-filter%3Aretweets%20url%3Aspeakerdeck.com
                headers:
                    Authorization:  Bearer XXXX
            result: the_message
        - define:
            assign:
                - project: "silverbirder-hot-tech-slides"
                - collection: "Tweet"
                - i: 0
        - check_condition:
            switch:
            - condition: ${len(the_message.body.statuses) > i}
              next: iterate
            next: exit_loop
        - iterate:
            assign:
            - document: ${the_message.body.statuses[i].id_str}
            next: write_2
        - write_2:
                call: http.request
                args:
                    url: ${"https://firestore.googleapis.com/v1/projects/"+project+"/databases/(default)/documents/"+collection+"/"+document}
                    auth:
                        type: OAuth2
                    method: PATCH
                    body:
                        name: ${"projects/"+project+"/databases/(default)/documents/"+collection+"/"+document}
                        fields:
                            text: ${the_message.body.statuses[i].text}
                next: set_1
        - set_1:
            assign:
            - i: ${i+1}
            next: check_condition
        - exit_loop:
            return: "END"